adding 'organized data' module
mattfazza/synapse_interactive_docs pull request #3
Opened 2021-04-08 18:29 UTC by kthrog

2021-04-09 23:06 UTC, mattfazza commented on organize_data/organize_data.ipynb
> +    "mySandbox = syn.get('')"
I have a location for us to create folders now: `syn25488570` (:

2021-04-09 23:31 UTC, mattfazza commented on organize_data/organize_data.ipynb
> +    "`syn.get` retrieves an entity from Synapse, in this case, an entire project. ([Learn more.](https://python-docs.synapse.org/build/html/index.html?highlight=syn%20get#synapseclient.Synapse.get))
If we go with the Syn id above then the wording here needs to change 🤷🏼‍♀️

2021-04-09 23:43 UTC, mattfazza requested changes
Wow, this is really good @kthrog .  Since I created the Synapse Interactive Onboarding folder, I proposed a couple of changes to this notebook!  Thanks for piecing this together 🥇

2021-04-12 16:44 UTC, kthrog commented
Great proposed changes -- I'll get to these in a bit, hopefully later this week!

2021-04-17 00:18 UTC, kthrog commented
Okay, @mattfazza -- this should be all set! I made your changes, but looks like I can't actually merge the PR as I don't have write access to the repo. However, please feel free to merge this in.

2021-04-19 19:13 UTC, merged